In [1]:
from selenium import webdriver
from bs4 import BeautifulSoup

from os import path
import time
from datetime import datetime

from pandas import DataFrame, read_excel, concat

import re
import sys, configparser

In [7]:
destination_dir = './'
last_file = 'inec_ipc_last'
incremental_file = 'inec_ipc_incremental'

url = "https://inec.gob.pa"
chromeOptions = webdriver.ChromeOptions()
##chromeOptions.add_argument("--headless")
browser = webdriver.Chrome('./driver/chromedriver.exe', options=chromeOptions)
browser.implicitly_wait(30)
browser.get(url)

In [8]:
soup = BeautifulSoup(browser.page_source, 'lxml')

plot = soup.find_all(id='graficas_graficaIndicadoresImageMap')[0]
points = plot.find_all('area', {'shape': 'circle'})

In [9]:
def monthToNum(shortMonth):
    return str({
    'Ene' : 1,
    'Feb' : 2,
    'Mar' : 3,
    'Abr' : 4,
    'May' : 5,
    'Jun' : 6,
    'Jul' : 7,
    'Ago' : 8,
    'Sep' : 9, 
    'Oct' : 10,
    'Nov' : 11,
    'Dic' : 12
    }[shortMonth])


df = []
today = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")

for p in points:
    string = p.get('alt')

    date, value = re.findall(r'([a-zA-Z]{3}\s\d{4}).*Valor:\s(.*)', string)[0]
    mes = date[:3]
    date = date.replace(mes, monthToNum(mes))
    date = datetime.strptime(date, '%m %Y')

    vals = [date, value, today]
    df.append(vals)

#df = pd.DataFrame(df, columns=['date', 'value', 'last_update_utc'])
df = DataFrame(df, columns=['date', 'value', 'last_update_utc'])
df.to_excel(f"{destination_dir}{last_file}.xlsx", index=None)

In [10]:
df

         date value      last_update_utc
0  2020-06-01  -1.6  2021-01-10 21:50:10
1  2020-05-01  -2.5  2021-01-10 21:50:10
2  2020-04-01  -2.4  2021-01-10 21:50:10
3  2020-03-01  -0.8  2021-01-10 21:50:10
4  2020-02-01     0  2021-01-10 21:50:10
5  2020-01-01   0.4  2021-01-10 21:50:10
6  2019-12-01  -0.1  2021-01-10 21:50:10
7  2019-11-01  -0.3  2021-01-10 21:50:10
8  2019-10-01  -0.7  2021-01-10 21:50:10
9  2019-09-01  -0.6  2021-01-10 21:50:10
10 2019-08-01  -0.6  2021-01-10 21:50:10
11 2019-07-01  -0.3  2021-01-10 21:50:10
12 2019-06-01  -0.5  2021-01-10 21:50:10
13 2019-05-01     0  2021-01-10 21:50:10
14 2019-03-01  -0.2  2021-01-10 21:50:10
15 2019-02-01  -0.5  2021-01-10 21:50:10
16 2019-01-01  -0.3  2021-01-10 21:50:10
17 2018-12-01   0.2  2021-01-10 21:50:10
18 2018-11-01   0.8  2021-01-10 21:50:10
19 2018-10-01     1  2021-01-10 21:50:10
20 2018-09-01   0.8  2021-01-10 21:50:10
21 2018-08-01   1.1  2021-01-10 21:50:10
22 2018-07-01   1.3  2021-01-10 21:50:10
23 2018-06-01   1.2  2021-01-10 21:50:10
24 2018-05-01   0.8  2021-01-10 21:50:10
25 2018-04-01   0.8  2021-01-10 21:50:10
26 2018-03-01   0.6  2021-01-10 21:50:10
27 2018-02-01   0.4  2021-01-10 21:50:10
28 2018-01-01   0.4  2021-01-10 21:50:10
29 2017-12-01   0.5  2021-01-10 21:50:10
30 2017-11-01   0.4  2021-01-10 21:50:10
31 2017-10-01   0.5  2021-01-10 21:50:10
32 2017-09-01   0.8  2021-01-10 21:50:10
33 2017-08-01   0.7  2021-01-10 21:50:10
34 2017-07-01   0.4  2021-01-10 21:50:10
35 2017-06-01   0.7  2021-01-10 21:50:10
36 2017-05-01   0.8  2021-01-10 21:50:10
37 2017-04-01     1  2021-01-10 21:50:10
38 2017-03-01   1.5  2021-01-10 21:50:10
39 2017-02-01   1.9  2021-01-10 21:50:10
40 2017-01-01   1.6  2021-01-10 21:50:10